### ISSUE TITLE
Project logo is lossy/blurry

### ISSUE THREAD

**Issue by kenchris** [htacg/html-tidy.org#1]
Doesn't look nice/professional. Probably needs to be redone if a non lossy version doesn't exist

**Comment by anssiko** [comment]
Ping @balthisar for lossless logo assets since he seems to have a [standalone logo](http://www.balthisar.com/assets/images/blog/tidy-html5-logo@2x-84d580bf.png) on his site.

**Comment by balthisar** [comment]
Can you provide a link to where blurry/lossy logos are being used? I'll get those fixed up right away.

Logo sources are in our community repository: https://github.com/htacg/community/tree/master/proposals_logos

Illustrator sources and SVGs are there, all vector art, so there's no reason anyone should have lossy logos.

Hmmm... looking at our own web pages it looks like there are some compression artifacts due to the backgrounds. I'll have to try to find time to improve those. But if there's someplace other than the banners where the logos are used, a heads-up would be appreciated.

**Comment by anssiko** [comment]
I think @kenchris referred to the logo on http://www.html-tidy.org/ that is combined with the background and scaled too large. This one: http://www.html-tidy.org/assets/images/green-abstract-background.jpg

I think a new version of that background with a bigger logo overlaid on top would be a quick fix. Alternatively, creating a transparent logo that is positioned on top of the background would offer more flexibility and be more future proof.

**Comment by balthisar** [comment]
@anssiko, thanks. Pretty bad compression artifacts. I'll have a look at it in the next few days.

**Comment by balthisar** [comment]
@kenchris, @anssiko, I finally had some time to clean this up. The SVG should be nice and clean at any resolution now.

**Comment by anssiko** [comment]
@balthisar Thanks for the updated SVG assets, they look awesome!

I submitted a PR do fix a related issue I discovered while testing the updated site on mobile, see PR #2.
