### ISSUE TITLE
Segfault of example program

### ISSUE THREAD

**Issue by NoelM** [htacg/html-tidy.org#13]
Dear all,

I remarked that the program presented within the post [2000-04-01-part_sample_program](https://github.com/htacg/html-tidy.org/blob/gh-pages/developer/_posts/2000-04-01-part_sample_program.md) produces a `SEGFAULT` signal if it used as if.

```
noelm@computer:~/workspace/tidy-html5$ gcc -Wall -g -I./include/ -o basic basic.c -L./build/ -ltidy
noelm@computer:~/workspace/tidy-html5$ ./basic 
Tidying:	<title>Foo</title><p>Foo!
A severe error (-1) occurred.
Segmentation fault (core dumped)
```
with `basic.c` which contains exactly the example code mentioned before.

By running `gdb` I observed with a breakpoint at line 40:
```
(gdb) l 40  
40	  tidyBufFree( &output );
(gdb) b 40
(gdb) r
(gdb) p output
$1 = {allocator = 0x0, bp = 0x0, size = 0, allocated = 0, next = 0}
(gdb) c
```
then it _segfaults_.

I'm on my way to find this bug by comparing `console/tidy.c:int main()` and the example code.

Regards,
Noel.

**Comment by NoelM** [comment]
After debugging the program, I observed that the call to `tidyOptSetBool` returns `no`:
```
Breakpoint 2, main (argc=1, argv=0x7fffffffdfa8) at basic.c:17
17        ok = tidyOptSetBool( tdoc, TidyXhtmlOut, yes );  // Convert to XHTML
(gdb) p ok
$3 = no
```
Thus I removed this option of converting to XHTML, and the formating of `tidy` worked well. Another solution I proposed was to change option to:
```c
Bool ok = tidyOptSetBool( tdoc, TidyHtmlOut, yes );  // Convert to HTML
```
which works also.

But it appears strange that the `TidyXhtmlOut` which is still present within `config.c` returns a `no`.

**Comment by geoffmcl** [comment]
@NoelM thank you for the issue, but the source link you gave appears wrong...

I think you are referring to the sample program at - https://github.com/htacg/html-tidy.org/blob/gh-pages/developer/_posts/2000-04-01-part_sample_program.md - please confirm?

If this is the source, it is also available in my [tidy-test](https://github.com/geoffmcl/tidy-test) repo, namely [src/sample.c](https://github.com/geoffmcl/tidy-test/blob/master/src/sample.c)... I just rebuilt the test apps, and have no problem running the `sample` app, in windows and unix... this is the `windows` output, but get the same in unix -

```
F:\Projects\tidy-test\build.x64>release\sample
Tidying:        <title>Foo</title><p>Foo!

Diagnostics:

line 1 column 1 - Warning: missing <!DOCTYPE> declaration
line 1 column 19 - Warning: inserting implicit <body>
Info: Document content looks like XHTML5
Tidy found 2 warnings and 0 errors!


And here is the result:

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Windows version 5.7.27" />
<title>Foo</title>
</head>
<body>
<p>Foo!</p>
</body>
</html>

F:\Projects\tidy-test\build.x64>echo %ERRORLEVEL%
1
```

I can not see any obvious error in your `gcc` build instructions of `basic.c`... maybe someone else will see the problem...

**BUT**, as your debug indicates, it does not get past the `tidyOptSetBool` step... it is a **broken** program!... you would need to build a **debug** tidy library, and trace into that API call... it should **never** return `no`... we have to learn, understand **WHY**?

And it is even more interesting, that you changed that to `ok = tidyOptSetBool( tdoc, TidyHtmlOut, yes );`, and it works... **THIS IS THE MYSTERY!** I can only think of some `libTidy` version confusion... or something... help...

Now, agreed, it does point out, that in the event of such a **catstophic** failure of `libTidy` to return `yes`, later causes a segfault!

While it is only a **sample** code, it should not do that... 

Those last two `tidyBufFree` calls need to be within an `if (rc >= 0) { /* do buffer frees */ }`, or something... 

A deeper fix would be in `libTidy` itself...

In in the `tidyBufFree` API call, although the `buf.allocator` is **not** used, a `null`, can cause a segfault... this could be avoided... but that is an issue to be raised on the `libTdiy` [issues](https://github.com/htacg/tidy-html5/issues) ... to be discussed... and potentually **fixed**... such that the given sample code would not be a problem, ever...

And it should be noted that that **same** sample code is in the API [docs](http://api.html-tidy.org/tidy/tidylib_api_next/libtidy_04.html)... this suggest `libTidy` should be fixed... it seems the code `TidyBuffer output = {0};tidyBufFree( &output );` just should **not** be a problem... will try to find time to test, and raise as issue... unless someone beats me to it...

But here, in this issue, at this moment more puzzled why the API failed, in your build of an app, using `libTidy`... that's strange...

Maybe you will get a chance to clone my test-tidy repo, and run `./sample` and see if there is any problem...

Lots to test... Look forward to further feedback... thanks...

**Comment by NoelM** [comment]
Sorry for the dead link (now corrected), it's this sample code I use: https://github.com/htacg/html-tidy.org/blob/gh-pages/developer/_posts/2000-04-01-part_sample_program.md

### Diagnostics

Thus I complied and ran my code with 4 flavors :
- Ubuntu 18.04 + `libtidy.so` ❌ 
- Ubuntu 18.04 + `libtidys.a` ✅ 
- MacOS + `libtidy.so` ✅ 
- MacOS + `libtidys.a` ✅ 

Consequently, I checked the linking of the code, and I observed:
```
noel@computer:~/workspace/tidy-html5$ gcc -Wall -g -I./include -o sample sample.c -L./build -ltidy
noel@computer:~/workspace/tidy-html5$ ldd sample
	linux-vdso.so.1 (0x00007ffd1d19b000)
	libtidy.so.5 => /usr/lib/libtidy.so.5 (0x00007fedfb1cb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fedfadda000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fedfb681000)
```
so it appears that this is not linked to the lib within `${pwd}/build` of my work directory. Actually, when I run this:
```
noel@computer:~/workspace/tidy-html5$ ls -alrth /usr/lib/libtidy.so*
-rw-r--r-- 1 root root 717K août   4  2016 /usr/lib/libtidy.so.5.2.0
lrwxrwxrwx 1 root root   16 juil.  8 14:03 /usr/lib/libtidy.so.5 -> libtidy.so.5.2.0
```
so it refers to my Ubuntu's installation date the 8th of July. While the package manager does not show this installed:
```
noel@computer:~/workspace/tidy-html5$ apt search tidy
[...]
tidy/bionic 1:5.2.0-2 amd64
  HTML/XML syntax checker and reformatter
[...]
```
This mean that by default a version of `libtidy` is installed within Ubuntu 18.04.

### `libtidy` fix

I totally agree with your interpretation:
>In in the tidyBufFree API call, although the buf.allocator is not used, a null, can cause a segfault... this could be avoided... but that is an issue to be raised on the libTdiy issues ... to be discussed... and potentually fixed... such that the given sample code would not be a problem, ever...

I will open an issue within `tidy-html5` in order to fix this problem of unallocated `TidyBuffer` variable.

### API documentation fix

This looks strange to mention a code block such as ` if (rc >= 0) { /* do buffer frees */ }` in the documentation. Actually, this uninitialized buffer comes from a fail of function applied to the `TidyDoc tdoc;` (`Bool ok = tidyOptSetBool( tdoc, TidyHtmlOut, yes );`) variable, and does not relate directly to the `TidyBuffer output;` variable.

Perhaps, one could mention this within the API documentation:
```
if (buffer->allocator) {
  tidyBufFree(&buffer);
}
```
which explicitly verifies that this is allocated ? _While I consider the proper way is to implemented this check within the function `tidyBufFree` directly._

Regards,
Noel

**Comment by geoffmcl** [comment]
@NoelM maybe you have solved the **mysterious** `tidyOptSetBool( tdoc, TidyHtmlOut, yes )` **failure**...

Certainly **mixed** tidy versions, between the include headers, and the library can do that...

There are **substantial** enum changes in the `tidyenum.h` header, between `5.2.0`, and the current `5.7.xx` - chaulk and cheese ;=)) can **not** be mixed...

Your gcc command includes `-I./include`, presumably in the cloned `tidy-html5` folder, that may mean it finds a recent `tidyenum.h`, ...

While the `-L./build` does **not** have the same effect! Maybe that should be `-L./build/cmake' anyway... not sure...

And then `/usr/lib/libtidy.so -> libtidy.so.5 -> libtidy.so.5.2.0` is found at **runtime**... oops... catastroph!

You might get a different result if `sample.c` is moved to `build/cmake`, built, and run there... That would/could work in Windows, where the apps runtime folder is the first searched, when resolving DLL's needed... but not so fully sure how `ldd` resolves shared library locations in unix... have used `LD_LIBRARY_PATH=/path/to/lib` successfuly in other projects... could work for `sample`...

So if the app is built using the local `include/tidyenum.h`, the `TidyXhtmlOut` would be 98, 0x62... 

In `libtidy.so.5.2.0`, that is the **same** value as `N_TIDY_OPTIONS`, and `TidyXhtmlOut` would in fact be 26, thus your app would **fail** in the code `Bool status = ( optId < N_TIDY_OPTIONS );`, leading to exposure in the sample code to another type of **failure**... a segfault in `tidyBufFree`...

How you want to fix, update, your system is of course up to you... 

If you want the latest `next` tidy, I would suggest, like in [BUILD.md](https://github.com/htacg/tidy-html5/blob/next/README/BUILD.md) -

```
$ cd ~/workspace/tidy-html5
$ git checkout next # if not presently on 'next'!
$ git pull # if needed...
$ cd build/cmake
$ cmake ../.. -DCMAKE_INSTALL_PREFIX=/usr [-DCMAKE_BUILD_TYPE=Release|Debug]
$ make
$ sudo make install # if release build...
```

Note well the `-DCMAKE_INSTALL_PREFIX=/usr`, otherwise cmake defaults to `/usr/local`, UGH! and you can get into a mess, with 2 versions installed...

Then your tidy headers, and libraries, would match up... and `ls -alrth /usr/lib/libtidy.so*` should show like `/usr/lib/libtidy.so.5 -> libtidy.so.5.7.xx`, currently 28...

And then you should be able to compile the `sample` **anywhere**, outside of tidy source, without using `-Isomething`, nor the `-Lsomething`... but still with `-ltidy` of course... and it should compile, and run correctly...

Now, with this **revelation**, I am **not** sure we do need to modify `libTidy`, **nor** change the `docs/sample` code... but am open to discussion on this... in the appropriate issue...

We should **not** try to paste over such a version clash... in your case it was this segfault that alerted you to a problem... like you tried, change that to another value, and all looks fine... a hidden bug... something other than the expected option was set... more difficult to tackle...

Look forward to further feedback... hopefully that you got it sorted... thanks...

**Comment by NoelM** [comment]
Thank you for the reply. Actually, this bug raises from this cross linking of `libTidy`. However, one could imagine something like:
```c
#include <tidy.h>
int main() {
  TidyBuffer output_buf;
  char* html_to_analyze;
  /*
   * block of code using `html_to_analyze` but not `output_buf`
   */
  tidyBufFree(&output_buf); // this will produce SEGFAULT signal
  return 0;
}
```
This is what I want to propose, preventing that a `tidyBufFree` of something not allocated does not produces `SEGFAULT`. Even if I consider that the developer should verify used values within its code `g++ -Wall`.

Regards,
Noël

**Comment by geoffmcl** [comment]
@NoelM thank you for the further feedback... agreed, but...

> preventing that a `tidyBufFree` of something not allocated does not produces `SEGFAULT`

While I agree that might be nice, **but** it is next to impossible to protect developers, in **this** particular case... namely `TidyBuffer output_buf [= {0}]; tidyBufFree(&output_buf);`  **BAD** code...

For instance, we can **not** use `if (buf->allocator)`, or any other structure members, since this/these could be anything, **any** value... and still lead to a SEGFAULT...

### Docs

I do agree that maybe the docs could/should be clearer... 

Like for say [TidyBuffer](http://api.html-tidy.org/tidy/tidylib_api_next/group__IO.html#struct__TidyBuffer), and [tidyBufFree](http://api.html-tidy.org/tidy/tidylib_api_next/tidybuffio_8h.html#a65aae9ae4b499e62038700f4792849fc), and others... 

But what to add? It is all `doxygen` comments in `tidybuffio.h`...

We could **add** say `tidyBufFree can only be called if the buffer has been initialized!`, 'used', or something **STRONGER**... 

Look forward to suggestions on this... but it should be as a **new** `libTidy` issue...

### Sample

Concerning the 'sample' code, I guess this should somehow convey **best practices**, from `libTidy` POV, which I do not think it does at the moment... 

It leaves **two** buffers potentially **uninitialized**, and/or **un-used**... yet tries to **free** them **regardless**... **ugh**, this does not seem too good... so suggest a patch like -

```diff
diff --git a/src/sample.c b/src/sample.c
index 39c0f0b..f3a791d 100644
--- a/src/sample.c
+++ b/src/sample.c
@@ -14,6 +14,9 @@ int main(int argc, char **argv )
   TidyDoc tdoc = tidyCreate();                     // Initialize "document"
   printf( "Tidying:\t%s\n", input );
 
+  tidyBufInit(&output);                            // Initialize "TidyBuffer" output,
+  tidyBufInit(&errbuf);                            // and message buffers
+
   ok = tidyOptSetBool( tdoc, TidyXhtmlOut, yes );  // Convert to XHTML
   if ( ok )
     rc = tidySetErrorBuffer( tdoc, &errbuf );      // Capture diagnostics
```

And **maybe** that should include removing, what readers/developers/users could mistake as **initialization**, namely `= {0}`... which it is **NOT**!

```diff
   const char* input = "<title>Foo</title><p>Foo!";
-  TidyBuffer output = {0};
-  TidyBuffer errbuf = {0};
+  TidyBuffer output;
+  TidyBuffer errbuf;
   int rc = -1;
```

Seek feedback on this patch... other ideas... etc... maybe it should be a **new** issue...

But @NoelM, you have not confirmed that you have been able to **avoid** the SEGFAULT... deal with multiple `tidy` versions... using the `sample` code, as is... can this be closed?

**Comment by NoelM** [comment]
Hello @geoffmcl, thanks for the reply. For me the problem discussed earlier seems fixed (`SEGFAULT` due to crossed lib versions).

However, the correction you presents looks great. In addition, a message within documentation which mention a mandatory `tidyBufInit` to avoid `SEGFAULTS` is relevant. Consequently, one should open a new issue.

All the best,
Noël.
